"""widen api_key prefix column

Revision ID: c664a62fc4a8
Revises: 7f06c2858558
Create Date: 2026-05-26 04:09:13.864217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c664a62fc4a8'
down_revision: Union[str, Sequence[str], None] = '7f06c2858558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
